// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MediatRvs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidShowHandlersToolWindowPackageString = "571c21e9-f882-4250-a22d-f90d47e22cfe";
        public static Guid guidShowHandlersToolWindowPackage = new Guid(guidShowHandlersToolWindowPackageString);

        public const string guidShowHandlersToolWindowPackageCmdSetString = "f728a930-07ec-4a65-aa89-2c1aaa98534a";
        public static Guid guidShowHandlersToolWindowPackageCmdSet = new Guid(guidShowHandlersToolWindowPackageCmdSetString);

        public const string IconsString = "77d336fb-b0cf-40c5-81d9-8a12e85018f1";
        public static Guid Icons = new Guid(IconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowHandlersToolWindowCommandId = 0x0100;
        public const int cmdidShowMessagesToolWindowCommand = 0x0101;
        public const int toolWindowLogo = 0x0004;
    }
}