name: Build

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]

    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v2
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build project
        shell: pwsh
        run: |
          .\build.ps1 --verbosity=diagnostic
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/**/*.vsix